<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="EPRURYAW0064" name="com.epam.anna_apushkina.test.expected_exceptions_tests.ExceptionTest" tests="3" failures="1" timestamp="23 Nov 2015 11:17:30 GMT" time="0.002" errors="0">
  <testcase name="exceptionTest" time="0.001" classname="com.epam.anna_apushkina.test.expected_exceptions_tests.ExceptionTest"/>
  <testcase name="exceptionMessageTest" time="0.000" classname="com.epam.anna_apushkina.test.expected_exceptions_tests.ExceptionTest"/>
  <testcase name="failTest" time="0.001" classname="com.epam.anna_apushkina.test.expected_exceptions_tests.ExceptionTest">
    <failure type="java.lang.AssertionError" message="Fail test message">
      <![CDATA[java.lang.AssertionError: Fail test message
	at org.testng.Assert.fail(Assert.java:94)
	at com.epam.anna_apushkina.test.expected_exceptions_tests.ExceptionTest.failTest(ExceptionTest.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
    </failure>
  </testcase> <!-- failTest -->
</testsuite> <!-- com.epam.anna_apushkina.test.expected_exceptions_tests.ExceptionTest -->
